#######################################
# Network
#######################################

# Redis ascolta sul container network
bind 0.0.0.0

port 6379

# Protezione base
protected-mode yes

#######################################
# General
#######################################

daemonize no

supervised no

loglevel notice

#######################################
# Persistence
#######################################

# Abilita Append Only File
appendonly yes

# Salva ogni secondo
appendfsync everysec


#######################################
# Snapshot
#######################################

save 900 1

save 300 10

save 60 10000

#######################################
# Memory
#######################################

# Limitiamo Redis per proteggere la VM
maxmemory 256mb

# Quando raggiunge il limite elimina cache vecchia
maxmemory-policy allkeys-lru

#######################################
# Security
#######################################

# La password verrà passata da environment
# oppure command line tramite docker run

#######################################
# Performance
#######################################

tcp-keepalive 60

timeout 0

#######################################
# Docker
#######################################

dir /data

dbfilename dump.rdb

appendfilename "appendonly.aof"

#######################################
# Clients
#######################################

maxclients 1000