server {

    listen 80;
    server_name dev.easyshop.gravities.net;

    return 301 https://$host$request_uri;
}



server {

    listen 443 ssl;
    server_name dev.easyshop.gravities.net;


    root /var/www/html/public;

    index index.php index.html;


    ssl_certificate /etc/nginx/ssl/cloudflare-origin.pem;
    ssl_certificate_key /etc/nginx/ssl/cloudflare-origin.key;


    ssl_protocols TLSv1.2 TLSv1.3;


    charset utf-8;


    location / {

        try_files $uri $uri/ /index.php?$query_string;

    }


    location = /favicon.ico {

        access_log off;
        log_not_found off;

    }


    location = /robots.txt {

        access_log off;
        log_not_found off;

    }


    error_page 404 /index.php;



    location ~ \.php$ {

        fastcgi_pass 127.0.0.1:9000;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        include fastcgi_params;

    }


    location ~ /\.(?!well-known).* {

        deny all;

    }

}