# Render deploy flow
name: Deploy DEV

on:
  workflow_run:
    workflows:
      - CI DEV
    types:
      - completed

jobs:
  deploy-web:
    name: Deploy DEV Web

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEV_DEPLOY_HOOK }}"

  deploy-worker:
    name: Deploy DEV Worker

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render worker deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEV_WORKER_DEPLOY_HOOK }}"
