name: Deploy DEV Web

on:
  workflow_run:
    workflows:
      - Build DEV Image
    types:
      - completed

jobs:
  deploy-web:
    environment: dev

    name: Deploy DEV Web

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: [self-hosted, web]

    permissions:
      contents: read
      packages: read

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check runner

        run: |
          hostname
          docker ps

      # Login GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3

        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Verify Image exist
      - name: Verify Image Exists

        run: |

          IMAGE_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          docker manifest inspect \
            ghcr.io/$IMAGE_NAME/easyshop-app:${{ github.sha }}

      # Generate Web ENV
      - name: Generate Web ENV

        run: |

          cat \
            infra/oracle/dev/base.env.example \
            infra/oracle/dev/web.env.example \
            > web.env

          sed -i "s|^APP_KEY=.*|APP_KEY=${{ secrets.APP_KEY }}|" web.env
          sed -i "s|^APP_URL=.*|APP_URL=${{ secrets.APP_URL }}|" web.env

          sed -i "s|^DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" web.env
          sed -i "s|^DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|" web.env
          sed -i "s|^DB_DATABASE=.*|DB_DATABASE=${{ secrets.DB_DATABASE }}|" web.env
          sed -i "s|^DB_USERNAME=.*|DB_USERNAME=${{ secrets.DB_USERNAME }}|" web.env
          sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" web.env

          sed -i "s|^REDIS_HOST=.*|REDIS_HOST=${{ secrets.REDIS_HOST }}|" web.env
          sed -i "s|^REDIS_PASSWORD=.*|REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}|" web.env
          sed -i "s|^REDIS_PORT=.*|REDIS_PORT=${{ secrets.REDIS_PORT }}|" web.env
          sed -i "s|^REDIS_USERNAME=.*|REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}|" web.env
          sed -i "s|^REDIS_SCHEME=.*|REDIS_SCHEME=${{ secrets.REDIS_SCHEME }}|" web.env

          sed -i "s|^FILESYSTEM_DISK=.*|FILESYSTEM_DISK=s3|" web.env

          sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}|" web.env
          sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}|" web.env

          sed -i "s|^AWS_DEFAULT_REGION=.*|AWS_DEFAULT_REGION=auto|" web.env

          sed -i "s|^AWS_BUCKET=.*|AWS_BUCKET=${{ secrets.R2_BUCKET }}|" web.env

          sed -i "s|^AWS_ENDPOINT=.*|AWS_ENDPOINT=${{ secrets.R2_ENDPOINT }}|" web.env

          sed -i "s|^AWS_URL=.*|AWS_URL=${{ secrets.R2_ENDPOINT }}/${{ secrets.R2_BUCKET }}|" web.env

          sed -i "s|^AWS_USE_PATH_STYLE_ENDPOINT=.*|AWS_USE_PATH_STYLE_ENDPOINT=true|" web.env

          sed -i "s|^RESEND_API_KEY=.*|RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}|" web.env

          sed -i "s|^MAIL_FROM_ADDRESS=.*|MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}|" web.env
          sed -i "s|^MAIL_FROM_NAME=.*|MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}|" web.env

          sed -i "s|^MAIL_SUPPORT_ADDRESS=.*|MAIL_SUPPORT_ADDRESS=${{ secrets.MAIL_SUPPORT_ADDRESS }}|" web.env
          sed -i "s|^MAIL_SUPPORT_NAME=.*|MAIL_SUPPORT_NAME=${{ secrets.MAIL_SUPPORT_NAME }}|" web.env

          sed -i "s|^MAIL_MARKETING_ADDRESS=.*|MAIL_MARKETING_ADDRESS=${{ secrets.MAIL_MARKETING_ADDRESS }}|" web.env
          sed -i "s|^MAIL_MARKETING_NAME=.*|MAIL_MARKETING_NAME=${{ secrets.MAIL_MARKETING_NAME }}|" web.env

          sed -i "s|^MAIL_ORDERS_ADDRESS=.*|MAIL_ORDERS_ADDRESS=${{ secrets.MAIL_ORDERS_ADDRESS }}|" web.env
          sed -i "s|^MAIL_ORDERS_NAME=.*|MAIL_ORDERS_NAME=${{ secrets.MAIL_ORDERS_NAME }}|" web.env

          sed -i "s|^MAIL_BILLING_ADDRESS=.*|MAIL_BILLING_ADDRESS=${{ secrets.MAIL_BILLING_ADDRESS }}|" web.env
          sed -i "s|^MAIL_BILLING_NAME=.*|MAIL_BILLING_NAME=${{ secrets.MAIL_BILLING_NAME }}|" web.env

      # Install Web Env
      - name: Install Web ENV

        run: |

          mkdir -p \
            /var/www/easyshop-web/shared/env

          cp web.env \
            /var/www/easyshop-web/shared/env/.env

      # Generate and install certificate TiDb
      - name: Generate TiDB Certificate

        run: |

          echo "${{ secrets.TIDB_CA_CERT }}" > tidb-ca.pem
          chmod 644 tidb-ca.pem

      - name: Install TiDB Certificate

        run: |

          mkdir -p \
            /var/www/easyshop-web/shared/certs

          mv tidb-ca.pem \
            /var/www/easyshop-web/shared/certs/tidb-ca.pem

          chmod 640 \
            /var/www/easyshop-web/shared/certs/tidb-ca.pem

      # Deploy app web
      - name: Deploy Web

        run: |

          chmod +x scripts/deploy/dev/web.sh

          scripts/deploy/dev/web.sh \
            ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/easyshop-app:${{ github.sha }}

      - name: Cleanup

        run: |
          rm -f web.env
          rm -f tidb-ca.pem
